import 'fake-indexeddb/auto';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {openStore,transact,parseCommand,explain} from '../tester/buypoint/interface-store.mjs';
const item={id:'coffee-12oz',name:'Coffee 12 oz',recommended:8,live:false,offers:[{price:9,store:'Fixture',url:'https://example.com',observed_at:'2026-09-04'}]};
let n=0;
const action=(type,value,source='screen',id=String(++n))=>({type,value,source,id});
async function setup(){return openStore('test-'+ ++n);}
test('chat and screen watch retries commit one alert and one receipt per request',async()=>{const db=await setup();await transact(db,action('product',item));await transact(db,action('watch',undefined,'chat','retry'));await transact(db,action('watch',undefined,'screen','retry'));const s=await transact(db,action('watch'));assert.equal(Object.keys(s.alerts).length,1);assert.equal(s.receipts.filter(r=>r.id==='retry').length,1);db.close();});
test('budget, target and complete evidence survive connection reopening',async()=>{const name='reload-'+ ++n;let db=await openStore(name);await transact(db,action('product',item));await transact(db,action('budget',7));await transact(db,action('target',6,'chat'));db.close();db=await openStore(name);const s=await transact(db);assert.match(explain(s),/Budget: \$7.00/);assert.match(explain(s),/Target: \$6.00/);assert.match(explain(s),/Above your budget/);assert.deepEqual(s.product,item);db.close();});
test('two connections serialize competing updates without lost receipts',async()=>{const name='tabs-'+ ++n,a=await openStore(name),b=await openStore(name);await Promise.all([transact(a,action('budget',20,'chat')),transact(b,action('explain'))]);const s=await transact(a);assert.equal(s.budget,20);assert.equal(s.receipts.length,2);a.close();b.close();});
test('failed commands do not mutate target or pretend to succeed',async()=>{const db=await setup();await transact(db,action('budget',10));const s=await transact(db,action('budget',-1,'chat'));assert.equal(s.budget,10);assert.equal(s.receipts.at(-1).status,'failed');assert.equal(s.receipts.at(-1).costUsd,null);assert.equal(s.receipts.at(-1).correctness,'not independently assessed');db.close();});
test('same request ID with different data aborts',async()=>{const db=await setup();await transact(db,action('budget',10,'chat','token'));await assert.rejects(transact(db,action('budget',999,'screen','token')),/different action/);assert.equal((await transact(db)).budget,10);db.close();});
test('target correction updates existing watch instead of leaving stale threshold',async()=>{const db=await setup();await transact(db,action('product',item));await transact(db,action('watch'));const s=await transact(db,action('target',7));assert.equal(s.alerts[item.id].target,7);assert.equal(s.receipts.at(-1).correction,true);db.close();});
test('command parsing and source receipt handle voice and reject unsupported instructions',async()=>{assert.deepEqual(parseCommand('Set budget to $15'),{type:'budget',value:15});assert.equal(parseCommand('delete everything').type,'unsupported');const db=await setup();const s=await transact(db,{...action('budget',18,'voice'),started:Date.now()-10});assert.equal(s.receipts[0].source,'voice');assert.ok(s.receipts[0].durationMs>=10);db.close();});
test('storage abort rejects without a false successful state',async()=>{const db=await setup();db.close();await assert.rejects(transact(db,action('budget',10)));});
